import {
  Bell,
  ArrowRightLeft,
  CheckCircle,
  MessageSquare,
  ShieldCheck,
  Star,
  CircleX,
} from "lucide-react";

export const mockNotifications = [
  {
    id: 1,
    userId: "1",
    icon: ArrowRightLeft,
    text: "มานะ ส่งคำขอแลกเปลี่ยน Macbook Air M1 กับ กล้อง Canon ของคุณ",
    time: "5 นาทีที่แล้ว",
    read: false,
    link: "/incoming-requests",
  },
  {
    id: 2,
    userId: "1",
    icon: ShieldCheck,
    text: "สมหญิง ได้ตอบรับคำของแลกเปลี่ยนกับคุณแล้ว นี้คือรหัสยืนยัน PIN สำหรับการแลกเปลี่ยนกับปิยะ: 5291",
    time: "1 นาทีที่แล้ว",
    read: false,
    link: "/exchange-tracking/m2",
  },
  {
    id: 3,
    userId: "1",
    icon: CheckCircle,
    text: "การแลกเปลี่ยนกับนภาสำเร็จแล้ว! กดเพื่อให้คะแนนรีวิว",
    time: "1 ชม. ที่แล้ว",
    read: false,
    link: "/review/m4",
  },
  {
    id: 4,
    userId: "3",
    icon: MessageSquare,
    text: "กมล ตอบรับคำขอแลกเปลี่ยนของคุณ",
    time: "3 ชม. ที่แล้ว",
    read: true,
    link: "/exchange-tracking/m3",
  },
  {
    id: 5,
    userId: "3",
    icon: Bell,
    text: "คุณมีรายการจับคู่ใหม่ 2 รายการ",
    time: "1 วัน ที่แล้ว",
    read: true,
    link: "/matching",
  },
  {
    id: 6,
    userId: "1",
    icon: Star,
    text: "ปิยะ ให้คะแนนรีวิวคุณ 5 ดาว พร้อมคอมเมนต์: 'แลกเปลี่ยนง่ายและรวดเร็วมากครับ!'",
    time: "2 วัน ที่แล้ว",
    read: true,
    link: "/profile",
  },
  {
    id: 7,
    userId: "2",
    icon: CircleX,
    text: "วรรณา ได้ยกเลิกการแลกเปลี่ยนของคุณ",
    time: "1 ชม. ที่แล้ว",
    read: false,
    link: "/review/m4",
  },
];
